<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       DB::table('products')->insert( [
            [
                'id' => 4,
                'name' => 'Iphone 16 promax',
                'description' => 'Iphone 16 promax',
                'price' => 30000000.00,
                'quantity' => 10,
                'image' => 'products/1dqxtvLvqAix9HVxd3SWx4EDWYOhGys74P9uYacZ.jpg',
                'brand_id' => 4,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:35:52',
                'updated_at' => '2025-04-16 23:36:04'
            ],
            [
                'id' => 5,
                'name' => 'SamSung GalaxyS23',
                'description' => 'SamSung GalaxyS23 ultra đến từ thương hiệu Mỹ',
                'price' => 1300000.00,
                'quantity' => 10,
                'image' => 'products/8XWSz1gMDeJh16T3oQIzdUkfoYS3X6278D0bucSo.jpg',
                'brand_id' => 3,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:37:33',
                'updated_at' => '2025-04-16 23:37:33'
            ],
            [
                'id' => 6,
                'name' => 'Iphone 11',
                'description' => 'Iphone 11 sản phẩm đã được phong sát',
                'price' => 7000000.00,
                'quantity' => 10,
                'image' => 'products/w79fs6vAMd3EehO9y74DUPDpq87r1pwaFlgREEnT.jpg',
                'brand_id' => 4,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:38:27',
                'updated_at' => '2025-04-16 23:38:27'
            ],
            [
                'id' => 8,
                'name' => 'Iphone 15 promax',
                'description' => 'là chiếc điện thoại đến từ nhà táo. Với hiệu năng vượt trội đem lại sự thú vị cho người sử dụng',
                'price' => 25000000.00,
                'quantity' => 10,
                'image' => 'products/VYzIhv4LGhOZdCGnGbZoxverXGiU0M3G9qbMaKOC.jpg',
                'brand_id' => 4,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:43:18',
                'updated_at' => '2025-04-16 23:52:25'
            ],
            [
                'id' => 9,
                'name' => 'Iphone 8',
                'description' => 'Là chiếc điện thoại đến từ nhà táo.Với hiệu năng vượt trội đem lại trải nghiệm người dùng ổn định',
                'price' => 10000000.00,
                'quantity' => 10,
                'image' => 'products/Fw73GHJ8wHt46QKPHkw3YvlbyRnzpRpGbhPYSYli.jpg',
                'brand_id' => 4,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:50:04',
                'updated_at' => '2025-04-16 23:50:04'
            ],
            [
                'id' => 10,
                'name' => 'xiaomi-redmi-note-13-pro-5g',
                'description' => 'xiaomi-redmi-note-13-pro-5g-xanhla mau xanh la',
                'price' => 12000000.00,
                'quantity' => 10,
                'image' => 'products/BRNEXepgQtDrgcgkMxQ1dzofuPV2jhgS3nUR8VQq.jpg',
                'brand_id' => 8,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:54:57',
                'updated_at' => '2025-04-16 23:54:57'
            ],
            // Continue with all other products...
            [
                'id' => 11,
                'name' => 'xiaomi-redmi-note-10-pro',
                'description' => 'xiaomi-redmi-note-10-pro-thumb-xam',
                'price' => 12000000.00,
                'quantity' => 10,
                'image' => 'products/jkfobLdQeny7oA36FvVOkFZqGk4mqt1ehrNALb9V.jpg',
                'brand_id' => 8,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:55:46',
                'updated_at' => '2025-04-16 23:55:46'
            ],
            [
                'id' => 12,
                'name' => 'xiaomi-redmi-12-pro-4g',
                'description' => 'xiaomi-redmi-12-pro-4g-xanh',
                'price' => 12000000.00,
                'quantity' => 10,
                'image' => 'products/gbl2R411xc7dTBj6KiwRg2v64Rfg8qsxvv3RZhkX.jpg',
                'brand_id' => 8,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:56:22',
                'updated_at' => '2025-04-16 23:56:22'
            ],
            [
                'id' => 14,
                'name' => 'vtalk-ear',
                'description' => 'vtalk-ear tai phone giá rẻ',
                'price' => 300000.00,
                'quantity' => 5,
                'image' => 'products/DS1GWaxvOxPIDbr78LwjHMattq6Yuw9b0EC5ydbp.jpg',
                'brand_id' => 7,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:58:08',
                'updated_at' => '2025-04-16 23:58:08'
            ],
            [
                'id' => 15,
                'name' => 'vi-vn-samsung-galaxy-chromebook',
                'description' => 'vi-vn-samsung-galaxy-chromebook-go-xe310xda-n4500-',
                'price' => 35000000.00,
                'quantity' => 2,
                'image' => 'products/MNxvONhrDdAc9TuSE9qCzW5KffYHISD3IzM4bcve.jpg',
                'brand_id' => 3,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:58:51',
                'updated_at' => '2025-04-16 23:58:51'
            ],
            // Additional products
            [
                'id' => 16,
                'name' => 'TiVi Sony2',
                'description' => 'TiVi Sony2 màn hình 1 tỉ màu xắc',
                'price' => 10000000.00,
                'quantity' => 10,
                'image' => 'products/WROKxTDO4tu2rlSkUj8R1v4qYHCCe0hDKCyfu3bO.jpg',
                'brand_id' => 5,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-16 23:59:45',
                'updated_at' => '2025-04-16 23:59:45'
            ],
            [
                'id' => 17,
                'name' => 'tivisony1.jpg',
                'description' => 'tivisony1',
                'price' => 10000000.00,
                'quantity' => 2,
                'image' => 'products/q7oUqAKOgvlynKn1fRFyxjrk24iRIU7PDMHaXQuW.jpg',
                'brand_id' => 5,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:02:04',
                'updated_at' => '2025-04-17 00:02:04'
            ],
            [
                'id' => 18,
                'name' => 'Tivi SamSung 4',
                'description' => 'Tivi SamSung 4 màn hình 1 tỉ sắc màu với trải nghiệm tuyệt đỉnh',
                'price' => 12000000.00,
                'quantity' => 10,
                'image' => 'products/VxZdWqJmmRU11k0koD29Tp72BmAE9fDX0Ay7zl6T.jpg',
                'brand_id' => 3,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:03:03',
                'updated_at' => '2025-04-17 00:03:03'
            ],
            [
                'id' => 19,
                'name' => 'tivisamsung3',
                'description' => 'tivisamsung3',
                'price' => 10000000.00,
                'quantity' => 10,
                'image' => 'products/KnJbcNFFQs0Q4Uzc9W2QORaGPccrApeaweHIsRyF.jpg',
                'brand_id' => 3,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:03:45',
                'updated_at' => '2025-04-17 00:03:45'
            ],
            [
                'id' => 20,
                'name' => 'tivisamsung2',
                'description' => 'tivisamsung2',
                'price' => 10000000.00,
                'quantity' => 12,
                'image' => 'products/Jgt1x4aBY8qNoOYimuxmj3GMG8I1ysYuHbvXPMOB.jpg',
                'brand_id' => 3,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:05:00',
                'updated_at' => '2025-04-17 00:05:00'
            ],
            [
                'id' => 21,
                'name' => 'tivisamsung1',
                'description' => 'tivisamsung1',
                'price' => 10000000.00,
                'quantity' => 10,
                'image' => 'products/daMksYfr7HzUrB7uoNoOKUUBxAhPl8wThrTex5re.jpg',
                'brand_id' => 3,
                'category_id' => 4,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:05:54',
                'updated_at' => '2025-04-17 00:05:54'
            ],
            [
                'id' => 22,
                'name' => 'tai-nghe-bluetooth-tws-oppo-enco-air-4-pro-etea1-den',
                'description' => 'tai-nghe-bluetooth-tws-oppo-enco-air-4-pro-etea1-den-1-750x500.jpg',
                'price' => 500000.00,
                'quantity' => 10,
                'image' => 'products/CXCqTnljNuSoxyM4h5RbnwOh64Vi09w78uxSsTdH.jpg',
                'brand_id' => 6,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:07:37',
                'updated_at' => '2025-04-17 00:07:37'
            ],
            [
                'id' => 23,
                'name' => 'tai-nghe-bluetooth-true-wireless-oppo-enco-buds-2-pro',
                'description' => 'tai-nghe-bluetooth-true-wireless-oppo-enco-buds-2-pro-e510',
                'price' => 2000000.00,
                'quantity' => 5,
                'image' => 'products/f9T4Dv1vv0mSy90zn7rCpEvcA6RZ2msj9JhZpwt3.jpg',
                'brand_id' => 6,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:08:25',
                'updated_at' => '2025-04-17 00:08:25'
            ],
            [
                'id' => 24,
                'name' => 'tai-nghe-apple-earpods-lightning',
                'description' => 'tai-nghe-apple-earpods-lightning-chinh-hang',
                'price' => 800000.00,
                'quantity' => 10,
                'image' => 'products/qvlLVwOYN8OdlI5H7cjOZedImiJpBgY3W4NU8sjJ.png',
                'brand_id' => 4,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:09:16',
                'updated_at' => '2025-04-17 00:09:16'
            ],
            [
                'id' => 25,
                'name' => 'sony-xperia-xz2',
                'description' => 'sony-xperia-xz2-cu',
                'price' => 10000000.00,
                'quantity' => 1,
                'image' => 'products/kQ783pxMjrt0l2pClOChi0kIoEkfnBOLcdu0Nf0r.jpg',
                'brand_id' => 5,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:10:19',
                'updated_at' => '2025-04-17 00:10:19'
            ],
            [
                'id' => 26,
                'name' => 'sony-xperia-xz1',
                'description' => 'sony-xperia-xz1 cu',
                'price' => 1000000.00,
                'quantity' => 1,
                'image' => 'products/TPTvjRitKGR2Oa8wS0urJX2nTcrFZQRuDH0cQyFI.jpg',
                'brand_id' => 5,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:11:03',
                'updated_at' => '2025-04-17 00:11:03'
            ],
            [
                'id' => 27,
                'name' => 'sony-xperia-5',
                'description' => 'sony-xperia-5-mark-3-8gb-128gb-ban-my-cu-99',
                'price' => 5000000.00,
                'quantity' => 1,
                'image' => 'products/xplCkIGvymtGlbpxK5Zh4FBEnaysM3u4985QUqhb.jpg',
                'brand_id' => 5,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:11:50',
                'updated_at' => '2025-04-17 00:11:50'
            ],
            [
                'id' => 28,
                'name' => 'sony-sn-898',
                'description' => 'sony-sn-898-bluetooth',
                'price' => 400000.00,
                'quantity' => 1,
                'image' => 'products/cnYuRLiMGj3FxmSZvbTJKc8EusjpZbxtZF5troRa.jpg',
                'brand_id' => 5,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:13:05',
                'updated_at' => '2025-04-17 00:13:05'
            ],
            [
                'id' => 29,
                'name' => 'sony-handy-portable-fmamwide-fm-radio',
                'description' => 'sony-handy-portable-fmamwide-fm-radio-icf-p27-black-icf-p27-bc',
                'price' => 10000000.00,
                'quantity' => 1,
                'image' => 'products/22JlG6lCVw8cHpZdgZZZTzvafDYModsMQUgT0cAr.jpg',
                'brand_id' => 5,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:13:56',
                'updated_at' => '2025-04-17 00:13:56'
            ],
            [
                'id' => 30,
                'name' => 'oppo-a9',
                'description' => 'oppo-a9',
                'price' => 6000000.00,
                'quantity' => 12,
                'image' => 'products/boEaxm4T7txgYSKi0GenS1lppmVO0x2B3I00TEia.jpg',
                'brand_id' => 6,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:18:26',
                'updated_at' => '2025-04-17 00:18:26'
            ],
            [
                'id' => 31,
                'name' => 'oppo-a55',
                'description' => 'oppo-a55-4g-thumb-new',
                'price' => 6000000.00,
                'quantity' => 10,
                'image' => 'products/m3dl9z9KGbegO61a6FA8UV8WSFg0u6TOstMHpkjx.jpg',
                'brand_id' => 6,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:19:04',
                'updated_at' => '2025-04-17 00:19:04'
            ],
            [
                'id' => 32,
                'name' => 'oppo-a91',
                'description' => 'oppo-a91',
                'price' => 7000000.00,
                'quantity' => 10,
                'image' => 'products/DXXpp0y31gq5cj5MRQZqosSbI5cqaW087PIVlYiS.jpg',
                'brand_id' => 6,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:19:43',
                'updated_at' => '2025-04-17 00:19:43'
            ],
            [
                'id' => 33,
                'name' => 'oppo-a92',
                'description' => 'oppo-a92-tim',
                'price' => 7000000.00,
                'quantity' => 10,
                'image' => 'products/03fVdvq4GOBD4iKtdWikSdzBDJFczOjiUqOaS50B.jpg',
                'brand_id' => 6,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:20:49',
                'updated_at' => '2025-04-17 00:20:49'
            ],
            [
                'id' => 34,
                'name' => 'Pin oppo',
                'description' => 'pin oppo',
                'price' => 500000.00,
                'quantity' => 20,
                'image' => 'products/8sNzLLwOEAfVUiPqIVQgrkgULXm2GURtBqwXLSDr.png',
                'brand_id' => 6,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:21:39',
                'updated_at' => '2025-04-17 00:21:39'
            ],
            [
                'id' => 35,
                'name' => 'pin-realme-8',
                'description' => 'pin-realme-8-rmx3085-blp841-zin2-hongchi',
                'price' => 700000.00,
                'quantity' => 20,
                'image' => 'products/CVUM1memfiH7PAhtELx4tX0RaPHnqDWmMlpkaiTv.jpg',
                'brand_id' => 7,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:22:17',
                'updated_at' => '2025-04-17 00:22:17'
            ],
            [
                'id' => 36,
                'name' => 'op-lung-iphone-16-pro-max',
                'description' => 'op-lung-iphone-16-pro-max',
                'price' => 300000.00,
                'quantity' => 30,
                'image' => 'products/UDqSHHFWFyA5EfEefMvZeIcyJq0277DacqGIROdy.jpg',
                'brand_id' => 4,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:23:20',
                'updated_at' => '2025-04-17 00:23:20'
            ],
            [
                'id' => 37,
                'name' => 'Xiaomi note-11-pro',
                'description' => 'Xiaomi note-11-pro',
                'price' => 6000000.00,
                'quantity' => 10,
                'image' => 'products/GqfSzFmfFJal8neNodCvtNYHguiIPg3QAitgcwFr.jpg',
                'brand_id' => 8,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:23:59',
                'updated_at' => '2025-04-17 00:23:59'
            ],
            [
                'id' => 38,
                'name' => 'mat-kinh-oppo',
                'description' => 'mat-kinh-oppo',
                'price' => 50000.00,
                'quantity' => 10,
                'image' => 'products/9uXgNPwKHrGS2QJYXc1Tacp8G8CQEQRlhDQUNaGZ.png',
                'brand_id' => 6,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:24:47',
                'updated_at' => '2025-04-17 00:24:47'
            ],
            [
                'id' => 39,
                'name' => 'man-hinh-samsung-galaxy-note-20',
                'description' => 'man-hinh-samsung-galaxy-note-20',
                'price' => 5000000.00,
                'quantity' => 5,
                'image' => 'products/6qs6hBBFRfSQU4zDXjJHIaJ6ZKeicIPrs3kgzYbT.jpg',
                'brand_id' => 3,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:25:18',
                'updated_at' => '2025-04-17 00:25:18'
            ],
            [
                'id' => 40,
                'name' => 'MacBook-Pro-16-inch-M1-Pro-M1-Max',
                'description' => 'MacBook-Pro-16-inch-M1-Pro-M1-Max',
                'price' => 40000000.00,
                'quantity' => 5,
                'image' => 'products/GXU8eJ2co696e1RgUgsaxcvnqgBNIStP14wVWEh0.png',
                'brand_id' => 4,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:26:02',
                'updated_at' => '2025-04-17 00:26:02'
            ],
            [
                'id' => 41,
                'name' => 'macbook_pro_14_inch_2023',
                'description' => 'macbook_pro_14_inch_2023_545l',
                'price' => 45000000.00,
                'quantity' => 3,
                'image' => 'products/MDNdZvIENwWWO9gBv2Z1YI1b1xrIlr3tuJIP97Ox.png',
                'brand_id' => 4,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:27:17',
                'updated_at' => '2025-04-17 00:27:17'
            ],
            [
                'id' => 42,
                'name' => 'macbook_pro_14_inch_2023',
                'description' => 'macbook_pro_14_inch_2023_545l',
                'price' => 45000000.00,
                'quantity' => 3,
                'image' => 'products/iuyaTB4ONzzJ8B1fO3aReGCRZTYLCGYekA2f5n8V.png',
                'brand_id' => 4,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:27:18',
                'updated_at' => '2025-04-17 00:27:18'
            ],
            [
                'id' => 43,
                'name' => 'macbook_pro_14_inch_2021_m1_pro',
                'description' => 'macbook_pro_14_inch_2021_m1_pro',
                'price' => 30000000.00,
                'quantity' => 5,
                'image' => 'products/pRIKY6nLWLOBnEPtdl1rP4F8kl0ri2jbvT9vGnFW.png',
                'brand_id' => 4,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:28:12',
                'updated_at' => '2025-04-17 00:28:12'
            ],
            [
                'id' => 44,
                'name' => 'apple-airpods-pro-2',
                'description' => 'apple-airpods-pro-2-2023',
                'price' => 1000000.00,
                'quantity' => 5,
                'image' => 'products/yZl1FaSK2yPQ6DAse9JA7zNg2AbMiLcnbKz0oR7p.jpg',
                'brand_id' => 4,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:29:27',
                'updated_at' => '2025-04-17 00:29:27'
            ],
            [
                'id' => 45,
                'name' => 'audio_airpod',
                'description' => 'audio_airpod',
                'price' => 3000000.00,
                'quantity' => 5,
                'image' => 'products/jyd6SYaVctSqJtrbCNNmonGT2XchbNMIhH2xYVD6.jpg',
                'brand_id' => 4,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:30:14',
                'updated_at' => '2025-04-17 00:30:14'
            ],
            [
                'id' => 46,
                'name' => 'avt-loa-sony',
                'description' => 'avt-loa-sony-ult-tower-10',
                'price' => 2000000.00,
                'quantity' => 3,
                'image' => 'products/HPSQMlQq18x4sSLaJhngWpzYbWUOjhCxfiLtxolS.jpg',
                'brand_id' => 5,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:31:03',
                'updated_at' => '2025-04-17 00:31:03'
            ],
            [
                'id' => 47,
                'name' => 'cauchy-passport-deep-grey',
                'description' => 'cauchy-passport-deep-grey-04-b-earphone-cover-opening-combination',
                'price' => 1000000.00,
                'quantity' => 1,
                'image' => 'products/mEk5OZGa2b5cls5f2ulExQhpc2YhwLvO5TvuBLOn.png',
                'brand_id' => 5,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:31:51',
                'updated_at' => '2025-04-17 00:32:04'
            ],
            [
                'id' => 48,
                'name' => 'coc-sac-nhanh-apple',
                'description' => 'coc-sac-nhanh-apple-20w-type-c-chinh-hang',
                'price' => 500000.00,
                'quantity' => 5,
                'image' => 'products/1eS2GuwD71N0n2mRqqnravzWcK3orlqnfMMtZDb5.png',
                'brand_id' => 4,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:32:55',
                'updated_at' => '2025-04-17 00:32:55'
            ],
            [
                'id' => 49,
                'name' => 'cu-sac-nhanh-samsung',
                'description' => 'cu-sac-nhanh-samsung-45w-chinh-hang',
                'price' => 15000000.00,
                'quantity' => 10,
                'image' => 'products/6F76BbzeQf3T9WwuwvwJgXLPh9Ju73NkWxJRKl3z.jpg',
                'brand_id' => 3,
                'category_id' => 3,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:33:57',
                'updated_at' => '2025-04-17 00:33:57'
            ],
            [
                'id' => 50,
                'name' => 'Laptop Sony Gaming Th4',
                'description' => 'Laptop Sony Gaming Th4',
                'price' => 40000000.00,
                'quantity' => 10,
                'image' => 'products/0edmZlgHVFcZoXdYfQfpstZP5p5eTG8L3VqchNr0.png',
                'brand_id' => 5,
                'category_id' => 5,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:34:53',
                'updated_at' => '2025-04-17 00:34:53'
            ],
            [
                'id' => 60,
                'name' => 'SamSung Zilip 6',
                'description' => 'SamSung Zilip 6',
                'price' => 40000000.00,
                'quantity' => 10,
                'image' => 'products/zVG6RMCXc0qFjQAWplGfJiR0QNyLBRjrejQsQO5x.jpg',
                'brand_id' => 3,
                'category_id' => 2,
                'rating' => 0.00,
                'reviews_count' => 0,
                'is_featured' => 0,
                'status' => 'active',
                'created_at' => '2025-04-17 00:52:43',
                'updated_at' => '2025-04-17 00:52:43'
            ],
        ]);
    }
}